CREATE TABLE CLIENTE
(id_cliente INT PRIMARY KEY,
nombre VARCHAR(30) NOT NULL,
apellido VARCHAR(30) NOT NULL,
email VARCHAR(45) NOT NULL
);

CREATE TABLE EMPLEADO
(id_empleado INT PRIMARY KEY,
nombre VARCHAR(30) NOT NULL,
apellido VARCHAR(30) NOT NULL,
edad INT NOT NULL,
domicilio VARCHAR(50) NOT NULL
);

CREATE TABLE SUCURSAL
(id_sucursal INT PRIMARY KEY,
nombre VARCHAR(30) NOT NULL,
direccion VARCHAR(50) NOT NULL
);

CREATE TABLE CATEGORIA
(id_categoria INT PRIMARY KEY,
nombre VARCHAR(30) NOT NULL
);

CREATE TABLE PRODUCTO
(id_producto INT PRIMARY KEY,
precio FLOAT NOT NULL,
descripcion VARCHAR(60) NOT NULL
);

CREATE TABLE VENTA
(id_venta INT PRIMARY KEY,
cantidad FLOAT NOT NULL
);

CREATE TABLE FACTURA
(id_factura INT PRIMARY KEY,
monto FLOAT NOT NULL,
forma_pago VARCHAR(15) NOT NULL,
fecha DATE NOT NULL
);

